Repository AlaskaAirlines/Icons, pull requests merged in 2020-04, with the labels that each got.

#31 Update package to repo name change
  README.md
  package-lock.json
  package.json
  src/data/icons.json
  src/icons/_legacy/arrowdown.svg
  src/icons/_legacy/arrowleft.svg
  src/icons/_legacy/arrowright.svg
  src/icons/_legacy/arrowup.svg
  src/icons/_legacy/chevrondown.svg
  src/icons/_legacy/chevronleft.svg
  src/icons/_legacy/chevronright.svg
  src/icons/_legacy/chevronup.svg
  src/icons/caret-down.svg
  src/icons/caret-left.svg
  src/icons/caret-right.svg
  src/icons/caret-up.svg
  src/icons/classic-checkmark.svg
  src/icons/close-lg.svg
  src/icons/close-sml.svg
  src/icons/close.svg
  src/icons/step-out-lg.svg
  src/icons/step-out.svg
Labels: Status: Complete / Ready to Merge, Type: Breaking Change

#33 feat: add 'food-and-drink' icon
  src/data/icons.json
  src/icons/food-and-drink.svg
Labels: Status: Complete / Ready to Merge, Type: Content/data

#32 Update docs to clarify new work
  .github/ISSUE_TEMPLATE/new-icon.md
  README.md
Labels: Status: Complete / Ready to Merge, Type: Documentation
